### PR TITLE
FIX #2093 warn in case we think VT-X is not enabled.

### LINKED ISSUE #2093: "This computer doesn't have VT-X/AMD-v enabled" (Bootcamp running Windows)
Whilst this is technically a Bootcamp issue, the recent change where Docker Machine checks if virtualization is enabled fails when running on a Macbook Pro using Windows. The virtualization flag is set to false when you boot straight into Windows for some unknown reason. A google suggests that there's no way around this other than first booting into OSX, then doing a soft boot into Windows each time :-/

Docker Machine was working fine for me until I updated to RC3 where it's now unusable, as it just throws the following error:

"This computer doesn't have VT-X/AMD-v enabled."

Is there any way this check can be bypassed? Perhaps with an explicit command line argument?

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dmp42** [comment]
LGTM

File: drivers/virtualbox/virtualbox.go [hunk 1]
```diff
@@ -205,7 +205,10 @@ func cmdOutput(name string, args ...string) (string, error) {
 
 // IsVTXDisabledInTheVM checks if VT-X is disabled in the started vm.
 func (d *Driver) IsVTXDisabledInTheVM() (bool, error) {
-	file, err := os.Open(path.Join(d.ResolveStorePath(d.MachineName), "Logs", "VBox.log"))
+	logPath := path.Join(d.ResolveStorePath(d.MachineName), "Logs", "VBox.log")
```
Comment (nathanleclaire) [inline drivers/virtualbox/virtualbox.go]: We almost ubiquitously use `filepath.Join` instead of `path.Join` for cross-platform compatibility reasons.  I'm not sure it strictly applies here, but can you please update to use that instead?

File: drivers/virtualbox/virtualbox.go [hunk 2]
```diff
@@ -205,7 +205,10 @@ func cmdOutput(name string, args ...string) (string, error) {
...
+	log.Debugf("Checking vm logs: %s", logPath)
+
+	file, err := os.Open(logPath)
```
Comment (nathanleclaire) [inline drivers/virtualbox/virtualbox.go]: Looks like you may be missing a `defer file.Close()` after this `err` check block?

File: drivers/virtualbox/virtualbox.go [hunk 3]
```diff
@@ -229,7 +232,11 @@ func (d *Driver) Create() error {
 	}
 
 	if d.IsVTXDisabled() {
-		return ErrMustEnableVTX
+		// Let's log a warning to warn the user. When the vm is started, logs
+		// will be checked for an error anyway.
+		// We could fail right here but the method to check didn't prove being
+		// bulletproof.
+		log.Warn("This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory.")
```
Comment (nathanleclaire) [inline drivers/virtualbox/virtualbox.go]: I agree that this being hidden away in the plugin output (behind `--debug`) is not ideal -- in the future we can talk about how to improve the situation.  Let me know if you have any ideas.

**Comment by nathanleclaire** [comment]
A few nitpicks but looks pretty good.

File: drivers/virtualbox/virtualbox.go (hunk 2 above)
Comment (dgageot) [inline drivers/virtualbox/virtualbox.go]: @nathanleclaire It is here on line 214. Isn't is the right way to do it?

**Comment by dgageot** [comment]
@nathanleclaire Thanks for your feedback. Ready to merge.

File: drivers/virtualbox/virtualbox.go (hunk 2 above)
Comment (nathanleclaire) [inline drivers/virtualbox/virtualbox.go]: My mistake -- I misread the diff.

**Comment by nathanleclaire** [comment]
LGTM
