### PR TITLE
Fixing JSON marshaling of large numbers during migration

### LINKED ISSUE #1998: V3 Config migration failure - can not unmarshal 7-digit (or larger) numbers into int
One of my machine's configs (a digitalocean machine) is failing to migrate to V3:

```console
$ docker-machine ls
Error attempting to invoke binary for plugin: json: cannot unmarshal number 5.393473e+06 into Go value of type int
```

I've dug into this and it looks like the second `json.Unmarshal` call (`json.Unmarshal(*rawHost.Driver, &m)`) in `host.MigrateHostV2ToHostV3` is converting the JSON number 5393473 into a `float64` - 5.393473e+06.

This seems to be something about how `encoding/json` [unmarshals numbers into `float64`s when using a `map[string]interface{}`](https://golang.org/pkg/encoding/json/#Unmarshal). The reason that this is only an issue with 7-digit numbers is that 6-digit `float64`s are displayed as-is, whereas larger numbers are displayed with scientific notation.

I'm going to hack on this and see if [`json.Decoder.UseNumber`](https://golang.org/pkg/encoding/json/#Decoder.UseNumber) can help...

### PR DESCRIPTION
**Pull request by hairyhenderson**
Fixes #1998

- Added some context to an error message - it's useful to know _which_
  plugin failed when invoking the binary failed
- Replaced `json.Umarshal` with a `json.Decoder`, so that the
  `UseNumber` function can be called, which prevents large integers from
  being interpreted as `float64`s.
- Fixed a couple `log.Warn` calls that should've been `log.Warnf`

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
@hairyhenderson Should be OK, can you paste an example of the config which was failing? (make sure to strip secrets out)  I'd like to write a test for it if possible.

**Comment by hairyhenderson** [comment]
@nathanleclaire - sure:

```json
{
  "ConfigVersion": 1,
  "Driver": {
    "IPAddress": "1.2.3.4",
    "SSHUser": "root",
    "SSHPort": 22,
    "MachineName": "hairyhenderson",
    "CaCertPath": "/Users/hairyhenderson/.docker/machine/certs/ca.pem",
    "PrivateKeyPath": "/Users/hairyhenderson/.docker/machine/certs/ca-key.pem",
    "SwarmMaster": true,
    "SwarmHost": "tcp://0.0.0.0:3376",
    "SwarmDiscovery": "token://deadbeefcafe",
    "AccessToken": "cafedeadbeef",
    "DropletID": 1234567,
    "DropletName": "",
    "Image": "ubuntu-14-04-x64",
    "Region": "nyc3",
    "SSHKeyID": 123456,
    "Size": "512mb",
    "IPv6": true,
    "Backups": false,
    "PrivateNetworking": true
  },
  "DriverName": "digitalocean",
  "HostOptions": {
    "Driver": "",
    "Memory": 0,
    "Disk": 0,
    "EngineOptions": {
      "ArbitraryFlags": [],
      "Dns": null,
      "GraphDir": "",
      "Env": null,
      "Ipv6": false,
      "InsecureRegistry": [],
      "Labels": [],
      "LogLevel": "",
      "StorageDriver": "",
      "SelinuxEnabled": false,
      "TlsCaCert": "",
      "TlsCert": "",
      "TlsKey": "",
      "TlsVerify": true,
      "RegistryMirror": [],
      "InstallURL": ""
    },
    "SwarmOptions": {
      "IsSwarm": true,
      "Address": "",
      "Discovery": "token://deadbeefcafe",
      "Master": true,
      "Host": "tcp://0.0.0.0:3376",
      "Image": "",
      "Strategy": "",
      "Heartbeat": 0,
      "Overcommit": 0,
      "TlsCaCert": "",
      "TlsCert": "",
      "TlsKey": "",
      "TlsVerify": false,
      "ArbitraryFlags": null
    },
    "AuthOptions": {
      "StorePath": "",
      "CaCertPath": "/Users/hairyhenderson/.docker/machine/certs/ca.pem",
      "CaCertRemotePath": "",
      "ServerCertPath": "/Users/hairyhenderson/.docker/machine/machines/hairyhenderson/server.pem",
      "ServerKeyPath": "/Users/hairyhenderson/.docker/machine/machines/hairyhenderson/server-key.pem",
      "ClientKeyPath": "/Users/hairyhenderson/.docker/machine/certs/key.pem",
      "ServerCertRemotePath": "",
      "ServerKeyRemotePath": "",
      "PrivateKeyPath": "/Users/hairyhenderson/.docker/machine/certs/ca-key.pem",
      "ClientCertPath": "/Users/hairyhenderson/.docker/machine/certs/cert.pem"
    }
  },
  "StorePath": "/Users/hairyhenderson/.docker/machine/machines/hairyhenderson"
}
```

In this case, the `DropletId` will get rendered as `1.234567e+06`, which is the bug :)

**Comment by nathanleclaire** [comment]
Argh, that should really be `string` field, not `int` O_O  But we're stuck with it for now I guess.

**Comment by hairyhenderson** [comment]
@nathanleclaire - yeah, I guess, but the issue remains for any JSON number with more than 6 digits :)

File: commands/commands.go [hunk 1]
```diff
@@ -113,7 +113,7 @@ func listHosts(store persist.Store) ([]*host.Host, error) {
 	for _, h := range hosts {
 		d, err := newPluginDriver(h.DriverName, h.RawDriver)
 		if err != nil {
-			return nil, fmt.Errorf("Error attempting to invoke binary for plugin: %s", err)
+			return nil, fmt.Errorf("Error attempting to invoke binary for plugin '%s': %s\n%s", h.DriverName, err, h.RawDriver)
```
Comment (nathanleclaire) [inline commands/commands.go]: Why the addition of `RawDriver` here?

Comment (hairyhenderson) [inline commands/commands.go]: Whoops. That was some debugging stuff I missed :). Good :eyes:!

Comment (nathanleclaire) [inline commands/commands.go]: Cool once that's removed cc me and I'm ready to merge this

**Comment by nathanleclaire** [comment]
Cool LGTM

**Comment by hairyhenderson** [comment]
woot, thanks.
