### PR TITLE
provisioner: update metadata before install or upgrade

### LINKED ISSUE #1114: 'machine create' with Ubuntu provisioner fails with "Error creating machine: Process exited with: 100. Reason was:  ()"
Creating a machine (I happened to be using the openstack driver) using an Ubuntu image fails if the os needs updates. 

The apt-get step to install curl is the point of failure, so to work around it, you can add 'sudo apt-get update && ' to the command in libmachine/provision/ubuntu.go::Package().

@ehazlett had seen this before, and he's going to fix it ASAP. I wanted to get it documented in the meantime.

### PR DESCRIPTION
**Pull request by ehazlett**
This issues an `apt-get update` for the Ubuntu provisioner so installs and updates do not fail.  This also helps if you package lists are out of date on the base OS.

Closes #1114

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Ah, nice.  I think we need some robustness around this kind of thing in general, for instance there was an issue about waiting for existing package stuff to finish before attempting our own.

File: libmachine/provision/ubuntu.go [hunk 1]
```diff
@@ -49,11 +49,14 @@ func (provisioner *UbuntuProvisioner) Service(name string, action pkgaction.Serv
 func (provisioner *UbuntuProvisioner) Package(name string, action pkgaction.PackageAction) error {
 	var packageAction string
 
+	updateMetadata := true
```
Comment (nathanleclaire) [inline libmachine/provision/ubuntu.go]: Is the idea that eventually this will be configurable / something the users can turn off?

File: libmachine/provision/ubuntu.go [hunk 2]
```diff
@@ -64,6 +67,13 @@ func (provisioner *UbuntuProvisioner) Package(name string, action pkgaction.Pack
 		name = "lxc-docker"
 	}
 
+	if updateMetadata {
+		// issue apt-get update for metadata
+		if _, err := provisioner.SSHCommand("sudo -E apt-get update"); err != nil {
```
Comment (nathanleclaire) [inline libmachine/provision/ubuntu.go]: Do we need the same `DEBIAN_FRONTEND` env var here?

File: libmachine/provision/ubuntu.go (hunk 1 above)
Comment (ehazlett) [inline libmachine/provision/ubuntu.go]: No the idea is that we shouldn't update the metadata when doing a remove.

File: libmachine/provision/ubuntu.go (hunk 2 above)
Comment (ehazlett) [inline libmachine/provision/ubuntu.go]: No -- it should just pull the latest package lists.

File: libmachine/provision/ubuntu.go (hunk 1 above)
Comment (nathanleclaire) [inline libmachine/provision/ubuntu.go]: Ah, it's a default, I see.

Probably a little nit-picky, but do you mind moving it into a var block like so at the top of the function?

```go
var (
    packageAction   string
    updateMetadata bool
)
```

**Comment by clnperez** [comment]
Anything I can do to help with this one?

**Comment by nathanleclaire** [comment]
@clnperez I think it's about ready to go, thanks though.

Evan other than my `var` block nit LGTM

File: libmachine/provision/ubuntu.go (hunk 1 above)
Comment (ehazlett) [inline libmachine/provision/ubuntu.go]: Yep -- good catch

**Comment by ehazlett** [comment]
updated -- @nathanleclaire PTAL

**Comment by nathanleclaire** [comment]
LGTM

**Comment by clnperez** [comment]
Thanks @ehazlett and @nathanleclaire!

**Comment by nathanleclaire** [comment]
> Thanks @ehazlett and @nathanleclaire!

:+1:

**Comment by ehazlett** [comment]
@clnperez yw :D
