### PR TITLE
Fixes #2595 remove fails when config.json is not found

### LINKED ISSUE #2595: docker-machine -f rm isn't very force.
if something goes wrong during a `docker-machine -f rm` - for example, on windows, the hyperv vm fails to shutdown, the `rm` removes the config.json, but the dir still exists.

you can reproduce this by just making an empy dir in the machines dir - `docker-machine -f rm` will be unable to clean up its area.

```
PS C:\WINDOWS\system32> docker-machine  create -d hyperv --hyperv-memory 8192 --hyperv-disk-size 40000 default
Host already exists: "default"
PS C:\WINDOWS\system32> docker-machine  rm -f default
Error removing host "default": open C:\Users\SvenDowideit\.docker\machine\machines\default\config.json: The system canno
t find the file specified.
PS C:\WINDOWS\system32> docker-machine  create -d hyperv --hyperv-memory 8192 --hyperv-disk-size 40000 default
Host already exists: "default"
PS C:\WINDOWS\system32> docker-machine  rm -f default
Error removing host "default": open C:\Users\SvenDowideit\.docker\machine\machines\default\config.json: The system canno
t find the file specified.
PS C:\WINDOWS\system32> cd C:\Users\SvenDowideit\.docker\machine\machines\
PS C:\Users\SvenDowideit\.docker\machine\machines> ls


    Directory: C:\Users\SvenDowideit\.docker\machine\machines


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       16/12/2015  10:23 AM                default


PS C:\Users\SvenDowideit\.docker\machine\machines> ls -la .\default\
Get-ChildItem : A parameter cannot be found that matches parameter name 'la'.
At line:1 char:4
+ ls -la .\default\
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

PS C:\Users\SvenDowideit\.docker\machine\machines> ls .\default\
PS C:\Users\SvenDowideit\.docker\machine\machines> docker-machine  rm -f default
Error removing host "default": open C:\Users\SvenDowideit\.docker\machine\machines\default\config.json: The system canno
t find the file specified.
PS C:\Users\SvenDowideit\.docker\machine\machines> rmdir .\default\
```

### PR DESCRIPTION
**Pull request by askb**
This issue occurs when `api.Load()` fails while loading
the `config.json` file, in case the config file is not present.
Refactored the code to handled `-y` and `-f` as documented.

Signed-off-by: Anil Belur <askb23@gmail.com>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Thanks for this @askb !

Couple of questions:

- Can you add some tests for this to `rm_test.go` please?
- Why not just log the `err` from `api.Load` instead of `return`ing?  It should have the same result, right?

**Comment by dgageot** [comment]
LGTM. Though the flow is starting to get really hard to read

File: commands/rm.go [hunk 1]
```diff
@@ -16,10 +16,18 @@ func cmdRm(c CommandLine, api libmachine.API) error {
...
+		h, loaderr := api.Load(hostName)
+		if loaderr != nil {
+			// On --force, continue to remove on-disk files/dir
+			if !force {
+				return fmt.Errorf("Error removing host %q: %s", hostName, loaderr)
+			}
+			log.Errorf("Error removing host %q: %s. Continuing on `-f`, host instance may by running", hostName, loaderr)
 		}
 
 		if !confirm && !force {
```
Comment (nathanleclaire) [inline commands/rm.go]: Since this checks for both `confirm` and `force`, why is it needed to set `confirm` on line 20 above?

**Comment by nathanleclaire** [comment]
Just one last nitpick -- please ensure that the added block to set `confirm` is needed.

I agree the code here is getting a little hairy - maybe we can pull some of the responsibility back into the `Store` / `api` with a `force` option like we had before.

After the nitpick, LGTM

File: commands/rm.go (hunk 1 above)
Comment (askb) [inline commands/rm.go]: yes, the block is not required and will be removed. Sorry for the confusion.

**Comment by askb** [comment]
Now UT has been included for remove. I agree, that the code flow may be a little tricky to follow and it may be good idea to move the force option into the `store/api`. I will try to look into it a little later and raise a separate PR, if possible. thanks again!

**Comment by dgageot** [comment]
LGTM
