### PR TITLE
Fix #4242 - Added quotes around IdentityFile path.

### LINKED ISSUE #4242: docker machine scp should quote path of the IdentityFile.
When executing command with **docker-machine scp**, 
if the username includes a space, the command will fail,
because of the IdenfityFile path not being quoted when passed to scp command.
So it should look something like
`-o IdentityFile="C:\Users\Lenovo X250\.docker\machine\machines\default\id_rsa"`

**Example:**
```
touch testme && docker-machine -D scp localhost:testme default:/home/docker/testme2 && docker-machine ssh default "ls
 -al /home/docker"
```

```
Docker Machine Version:  0.12.2, build 9371605
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:58782
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetSSHPort
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHKeyPath
(default) Calling .GetSSHHostname
(default) Calling .GetSSHUsername
{C:\Program Files\Git\usr\bin\scp.exe [C:\Program Files\Git\usr\bin\scp.exe -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -3 -o IdentitiesOnly=yes -o Port=59590 -o IdentityFile=C:\Users\Lenovo X250\.docker\machine\machines\default\id_rsa testme docker@127.0.0.1:/home/docker/testme2] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}
command-line line 0: garbage at end of line; "X250\\.docker\\machine\\machines\\default\\id_rsa".
lost connection
exit status 1
```

**Docker version:**
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:46:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Docker machine:**
docker-machine.exe version 0.12.2, build 9371605

### PR DESCRIPTION
**Pull request by Herbis**
Fixes #4242 
Added quotes around IdentityFile path to avoid a fatal error when a space character is present at the path.

### CODE REVIEW

**Comment by Herbis** [comment]
Sorry for missing that part @GordonTheTurtle 
Is signed now.

**Comment by Herbis** [comment]
Travis build error seems to be due to lint errors in files I did not modify. Is there something I need to do?
```
Successfully built e909ea453240
go build \
-o /go/src/github.com/docker/machine/bin/docker-machine \
 -tags "" \
-ldflags "-X `go list ./version`.GitCommit=`git rev-parse --short HEAD 2>/dev/null` -w -s"  ./cmd/machine.go
Congratulations! All commits are properly signed with the DCO!
drivers/azure/azure.go:393:2: redundant if ...; err != nil check, just return error instead.
drivers/azure/azure.go:436:2: redundant if ...; err != nil check, just return error instead.
drivers/exoscale/exoscale.go:458:2: redundant if ...; err != nil check, just return error instead.
drivers/hyperv/hyperv.go:180:2: redundant if ...; err != nil check, just return error instead.
drivers/vmwarevcloudair/vcloudair.go:448:2: redundant if ...; err != nil check, just return error instead.
drivers/vmwarevsphere/vsphere.go:938:2: redundant if ...; err != nil check, just return error instead.
libmachine/persist/filestore.go:56:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/arch.go:150:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/boot2docker.go:258:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/coreos.go:130:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/debian.go:141:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/rancheros.go:139:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/redhat.go:113:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/redhat.go:181:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/suse.go:205:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/ubuntu_systemd.go:151:2: redundant if ...; err != nil check, just return error instead.
libmachine/provision/ubuntu_upstart.go:160:2: redundant if ...; err != nil check, just return error instead.
make: *** [lint] Error 1
mk/validate.mk:18: recipe for target 'lint' failed
make: *** [build validate] Error 2
The command "USE_CONTAINER=true make "$TARGETS"" exited with 2.
0.01s$ [[ "$(find bin -type f -name docker-machine*)" != "" ]]
find: `bin': No such file or directory
The command "[[ "$(find bin -type f -name docker-machine*)" != "" ]]" exited with 1.
Done. Your build exited with 1.
```

**Comment by Herbis** [comment]
Hi @shin- ,
could you please let me know if anything needs changing? 
Thanks.

**Comment by shin-** [comment]
Sorry for the delayed response. I'll fix the linting in the coming week and ping you to rebase this PR afterwards. Thank you!

**Comment by shin-** [comment]
@Herbis I just merged #4266 - can you rebase your PR against the new master?

**Comment by Herbis** [comment]
@shin- Rebase complete :)

File: commands/scp.go [hunk 1]
```diff
@@ -177,7 +177,7 @@ func getInfoForScpArg(hostAndPath string, hostInfoLoader HostInfoLoader) (h Host
 	}
 
 	if h.GetSSHKeyPath() != "" {
-		args = append(args, "-o", fmt.Sprintf("IdentityFile=%s", h.GetSSHKeyPath()))
+		args = append(args, "-o", fmt.Sprintf(`IdentityFile="%s"`, h.GetSSHKeyPath()))
```
Comment (shin-) [inline commands/scp.go]: I just realized that a possibly better fix for this would be to use `%q` instead of `%s`, which would also take care of the odd case where the path itself contains quotes. WDYT?

Comment (Herbis) [reply commands/scp.go]: @shin- Agreed. Changes made.

**Comment by shin-** [comment]
Sweet, thank you!
